service: ndc-gating-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: dev
  environment:
    CONFIG_TABLE: ${self:service}-${self:provider.stage}-Config
    COUNTERS_TABLE: ${self:service}-${self:provider.stage}-Counters

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource:
            - arn:aws:dynamodb:us-east-1:${aws:accountId}:table/${self:service}-${self:provider.stage}-Config
            - arn:aws:dynamodb:us-east-1:${aws:accountId}:table/${self:service}-${self:provider.stage}-Counters

functions:
  check:
    handler: handler.check_ndc
    events:
      - httpApi:
          path: /check
          method: post

  increment:
    handler: handler.increment_failures
    events:
      - httpApi:
          path: /increment
          method: post

  config:
    handler: handler.update_config
    events:
      - httpApi:
          path: /config
          method: post

resources:
  Resources:
    ConfigTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-Config
        AttributeDefinitions:
          - AttributeName: provider
            AttributeType: S
        KeySchema:
          - AttributeName: provider
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    CountersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-Counters
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
